import type { Metadata } from "next";
import "./globals.css";

import Footer from "@/components/layout/footer";
import Header from "@/components/layout/header";
import { AuthProvider } from '@/lib/actions/authcontext';

export const metadata: Metadata = {
  title: "app 08/09/25",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <AuthProvider>
          <Header />
          {children}
          <Footer />
        </AuthProvider>
      </body>
    </html>
  );
}
